// Architecture Specification Template
// Story 8.1: Architecture Specification Template

import { v4 as uuidv4 } from 'uuid';
import { ArchitectureSpec, ArchitectureSection, SpecTemplateConfig } from './types.js';

// Default required sections for architecture specification
const DEFAULT_SECTIONS: Record<string, ArchitectureSection> = {
  overview: {
    title: 'Overview',
    content: '',
    required: true,
    fields: ['problem_statement', 'goals', 'constraints', 'assumptions']
  },
  dataModel: {
    title: 'Data Model',
    content: '',
    required: true,
    fields: ['entities', 'relationships', 'schema']
  },
  api: {
    title: 'API Design',
    content: '',
    required: true,
    fields: ['endpoints', 'request_response', 'authentication']
  },
  security: {
    title: 'Security',
    content: '',
    required: true,
    fields: ['authentication', 'authorization', 'data_protection', 'compliance']
  }
};

// Template prompts for each section
const SECTION_PROMPTS: Record<string, string[]> = {
  overview: [
    '## Problem Statement',
    'What problem does this project solve?',
    '',
    '## Goals',
    '- Goal 1: ',
    '- Goal 2: ',
    '- Goal 3: ',
    '',
    '## Constraints',
    '- Constraint 1: ',
    '',
    '## Assumptions',
    '- Assumption 1: '
  ],
  dataModel: [
    '## Entities',
    '| Entity | Attributes |',
    '|--------|------------|',
    '|        |            |',
    '',
    '## Relationships',
    'Describe the relationships between entities:',
    '',
    '## Schema',
    '```\n// Schema definition\n```'
  ],
  api: [
    '## Endpoints',
    '| Method | Path | Description |',
    '|--------|------|-------------|',
    '| GET    | /api/... | ... |',
    '',
    '## Request/Response',
    'Describe the request and response format:',
    '',
    '## Authentication',
    'Describe authentication mechanism:'
  ],
  security: [
    '## Authentication',
    'How will users authenticate?',
    '',
    '## Authorization',
    'What are the user roles and permissions?',
    '',
    '## Data Protection',
    'How will sensitive data be protected?',
    '',
    '## Compliance',
    'Any compliance requirements (GDPR, SOC2, etc.)?'
  ]
};

export class ArchitectureSpecTemplate {
  /**
   * Generate a new architecture specification template
   */
  static create(config: SpecTemplateConfig): ArchitectureSpec {
    const now = new Date().toISOString();
    const specId = uuidv4();

    // Build sections based on config
    const sections = this.buildSections(config);

    return {
      id: specId,
      version: '1.0.0',
      projectName: config.projectName,
      ...sections,
      createdAt: now,
      updatedAt: now
    };
  }

  /**
   * Build sections based on config
   */
  private static buildSections(config: SpecTemplateConfig): Pick<ArchitectureSpec, 'overview' | 'dataModel' | 'api' | 'security'> {
    const includeSections = config.includeSections || Object.keys(DEFAULT_SECTIONS);

    const sections: any = {};

    for (const sectionKey of includeSections) {
      if (DEFAULT_SECTIONS[sectionKey]) {
        sections[sectionKey] = {
          ...DEFAULT_SECTIONS[sectionKey],
          content: SECTION_PROMPTS[sectionKey]?.join('\n') || ''
        };
      }
    }

    return sections;
  }

  /**
   * Generate markdown template for a section
   */
  static getSectionTemplate(section: keyof typeof SECTION_PROMPTS): string {
    return SECTION_PROMPTS[section]?.join('\n') || '';
  }

  /**
   * Generate complete markdown template
   */
  static getMarkdownTemplate(spec: ArchitectureSpec): string {
    return `# Architecture Specification: ${spec.projectName}

**Version:** ${spec.version}
**Created:** ${spec.createdAt}

---

${spec.overview.content}

---

${spec.dataModel.content}

---

${spec.api.content}

---

${spec.security.content}

---

*This specification was generated by vibe-flow*
`;
  }

  /**
   * Get list of required fields for a section
   */
  static getRequiredFields(section: string): string[] {
    return DEFAULT_SECTIONS[section]?.fields || [];
  }

  /**
   * List all available sections
   */
  static getAvailableSections(): string[] {
    return Object.keys(DEFAULT_SECTIONS);
  }
}
