// InitHandler - Handles Claude Code integration initialization
import chalk from 'chalk';
import { promises as fs } from 'fs';
import { join } from 'path';

export interface InitOptions {
  // No specific options for init
}

export class InitHandler {
  async execute(_options: InitOptions): Promise<void> {
    console.log(chalk.blue('📝 Initializing Claude Code integration...'));

    try {
      const claudeDir = join(process.cwd(), '.claude');
      await fs.mkdir(claudeDir, { recursive: true });

      const settingsPath = join(claudeDir, 'settings.json');
      const settings = {
        mcpServers: {
          "vibe-flow": {
            command: "node",
            args: [join(process.cwd(), "dist", "cli.js"), "mcp", "--stdio"],
            env: {}
          }
        }
      };

      await fs.writeFile(settingsPath, JSON.stringify(settings, null, 2));
      console.log(chalk.green(`  ✅ Created .claude/settings.json`));

      const claudeMdPath = join(process.cwd(), 'CLAUDE.md');
      try {
        await fs.access(claudeMdPath);
        console.log(chalk.gray('   CLAUDE.md already exists'));
      } catch {
        const claudeMd = `# Project Notes

Generated by vibe-flow

## BMAD-METHOD Integration

This project uses vibe-flow for workflow orchestration.

### Commands
- \`vibe-flow start <name>\` - Start new project
- \`vibe-flow advance\` - Advance workflow
- \`vibe-flow status\` - Show status
- \`vibe-flow wrap-up\` - Execute wrap-up
- \`vibe-flow preflight\` - Run pre-flight checks
`;
        await fs.writeFile(claudeMdPath, claudeMd);
        console.log(chalk.green(`  ✅ Created CLAUDE.md`));
      }

      console.log(chalk.green('\n✅ Claude Code integration initialized!'));
      console.log(chalk.gray('\nRestart Claude Code to use vibe-flow tools.'));
    } catch (error: unknown) {
      console.error(chalk.red(`❌ Failed to initialize: ${(error as Error).message}`));
    }
  }
}
